set_property SRC_FILE_INFO {cfile:/media/sf_VMLinux/Projects/VivadoTutorials/rdf0281-kc705-base-trd-2014-2/k7_pcie_dma_ddr3_base/design/implement/vivado_flow_x4gen2/vivado_proj_1/k7_pcie_dma_ddr3_base_x4_gen2.srcs/sources_1/ip/mig_7x/mig_7x/user_design/constraints/mig_7x.xdc rfile:../vivado_proj_1/k7_pcie_dma_ddr3_base_x4_gen2.srcs/sources_1/ip/mig_7x/mig_7x/user_design/constraints/mig_7x.xdc id:1 order:EARLY scoped_inst:virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/media/sf_VMLinux/Projects/VivadoTutorials/rdf0281-kc705-base-trd-2014-2/k7_pcie_dma_ddr3_base/design/implement/vivado_flow_x4gen2/k7_pcie_dma_ddr3_base_x4_gen2.xdc rfile:../k7_pcie_dma_ddr3_base_x4_gen2.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:769 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:778 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:784 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:785 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y43 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y143 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y131 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y119 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y107 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:797 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:1 line:798 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:1 line:807 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:1 line:808 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:1 line:812 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_propagated_clock sys_clk_p
set_property src_info {type:XDC file:2 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y3  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out]
set_property src_info {type:XDC file:2 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y2  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out]
set_property src_info {type:XDC file:2 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y1  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out]
set_property src_info {type:XDC file:2 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y0  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out]
set_property src_info {type:XDC file:2 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out]
set_property src_info {type:XDC file:2 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out]
set_property src_info {type:XDC file:2 line:741 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out]
set_property src_info {type:XDC file:2 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out]
set_property src_info {type:XDC file:2 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out]
set_property src_info {type:XDC file:2 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out]
set_property src_info {type:XDC file:2 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y8  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out]
set_property src_info {type:XDC file:2 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y3 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y2 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y1 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y0 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y11 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y10 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y9  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y8  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in]
set_property src_info {type:XDC file:2 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y3  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo]
set_property src_info {type:XDC file:2 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y2  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo]
set_property src_info {type:XDC file:2 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y1  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo]
set_property src_info {type:XDC file:2 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y0  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo]
set_property src_info {type:XDC file:2 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo]
set_property src_info {type:XDC file:2 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo]
set_property src_info {type:XDC file:2 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo]
set_property src_info {type:XDC file:2 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo]
set_property src_info {type:XDC file:2 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo]
set_property src_info {type:XDC file:2 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo]
set_property src_info {type:XDC file:2 line:769 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y8  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo]
set_property src_info {type:XDC file:2 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y3  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y2  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y1  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y0  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y11 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y10 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y9  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:778 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y8  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo]
set_property src_info {type:XDC file:2 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y0 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i]
set_property src_info {type:XDC file:2 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i]
set_property src_info {type:XDC file:2 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i]
set_property src_info {type:XDC file:2 line:784 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y0 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i]
set_property src_info {type:XDC file:2 line:785 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i]
set_property src_info {type:XDC file:2 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i]
set_property src_info {type:XDC file:2 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y43  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y31  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y19  [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y7   [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y143 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y131 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y119 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y107 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts]
set_property src_info {type:XDC file:2 line:800 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y1 [get_cells virtual_pfifo_wrapper_inst/mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i]
set_property src_info {type:XDC file:2 line:864 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells pcie_clk_ibuf]
set_property src_info {type:XDC file:2 line:876 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:2 line:878 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:2 line:880 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:2 line:882 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:2 line:890 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_X0Y0 [get_cells pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_block_i]
set_property src_info {type:XDC file:2 line:895 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X5Y35 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:896 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y36 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:897 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y35 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:898 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y34 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:899 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y33 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:900 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y32 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:901 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y31 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:902 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X4Y30 [get_cells {pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:XDC file:2 line:924 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_block_i/PLPHYLNKUPN*]
set_property src_info {type:XDC file:2 line:925 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins pcie_inst/inst/inst/pcie_top_i/pcie_7x_i/pcie_block_i/PLRECEIVEDHOTRST*]
set_property src_info {type:XDC file:2 line:927 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets * -hierarchical -filter {NAME =~ */gt_top.gt_top_i/pipe_wrapper_i/*pipe_reset*/resetdone*}]
set_property src_info {type:XDC file:2 line:928 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[0].pipe_rate.pipe_rate_i/*}]
set_property src_info {type:XDC file:2 line:929 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[1].pipe_rate.pipe_rate_i/*}]
set_property src_info {type:XDC file:2 line:930 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[2].pipe_rate.pipe_rate_i/*}]
set_property src_info {type:XDC file:2 line:931 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_nets {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_lane[3].pipe_rate.pipe_rate_i/*}]
set_property src_info {type:XDC file:2 line:933 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S0]
set_property src_info {type:XDC file:2 line:934 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S1]
set_property src_info {type:XDC file:2 line:937 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_cells {pcie_inst/inst/inst/gt_top.gt_top_i/pipe_wrapper_i/pipe_reset.pipe_reset_i/cpllreset_reg*}]
set_property src_info {type:XDC file:2 line:976 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ *IGP/wr_preview/*wr_pntr_*}] -to [get_cells * -hierarchical -filter {NAME =~ *IGP/wr_preview/*Q_*}]
set_property src_info {type:XDC file:2 line:978 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ *IGP/wr_preview/*rd_pntr_*}] -to [get_cells * -hierarchical -filter {NAME =~ *IGP/wr_preview/*Q_*}]
set_property src_info {type:XDC file:2 line:980 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ *EGP/rd_preview/*wr_pntr_*}] -to [get_cells * -hierarchical -filter {NAME =~ *EGP/rd_preview/*Q_*}]
set_property src_info {type:XDC file:2 line:982 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ *EGP/rd_preview/*rd_pntr_*}] -to [get_cells * -hierarchical -filter {NAME =~ *EGP/rd_preview/*Q_*}]
set_property src_info {type:XDC file:2 line:1047 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/*rstblk/*wr_rst_asreg*}]
set_property src_info {type:XDC file:2 line:1048 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/*rstblk/*RST_FULL_GEN*}]
set_property src_info {type:XDC file:2 line:1049 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/*rstblk/*grst_full*rst_d*}]
set_property src_info {type:XDC file:2 line:1050 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/EGP/rd_preview/*rstblk/*rd_rst_asreg*}]
set_property src_info {type:XDC file:2 line:1053 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/u_memc_ui_top_axi/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/*rstblk/*RST_FULL_GEN*}]
set_property src_info {type:XDC file:2 line:1054 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/*rstblk/*rst_d1_reg*}]
set_property src_info {type:XDC file:2 line:1055 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/mp_mc_inst/mig_inst/u_mig_7x_mig/*init_calib_complete_r*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/*rstblk/*rst_d2_reg*}]
set_property src_info {type:XDC file:2 line:1059 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/sync_to_user_clk_*/sync_2reg_reg*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/U0/*/*rstblk/*RST_FULL_GEN*}]
set_property src_info {type:XDC file:2 line:1060 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/sync_to_user_clk_*/sync_2reg_reg*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/U0/*/*rstblk/*rd_rst_asreg*}]
set_property src_info {type:XDC file:2 line:1061 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/sync_to_user_clk_*/sync_2reg_reg*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/U0/*/*rstblk/*wr_rst_asreg*}]
set_property src_info {type:XDC file:2 line:1062 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/sync_to_user_clk_*/sync_2reg_reg*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/IGP/wr_preview/U0/*/*rstblk/*rst_d*}]
set_property src_info {type:XDC file:2 line:1064 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/sync_to_user_clk_*/sync_2reg_reg*}] -to [get_cells * -hierarchical -filter {NAME =~ */mp_pfifo_inst/multiple_pfifo.genblk1[*].pvfifo_ctlr_inst/vfifo_ctrl_inst/EGP/rd_preview/*/*rstblk/*rd_rst_asreg*}]
